### ISSUE TITLE
Cluster Sharding Example

### ISSUE THREAD

**Issue by synox** [akka/akka-samples#10]
I find Cluster Sharding hard to understand. An example would be great.

**Comment by ktoso** [comment]
Reactive Maps are the usual example for sharding: https://github.com/typesafehub/ReactiveMaps#master

Not sure if we want to move it into here.

**Comment by patriknw** [comment]
There is http://www.lightbend.com/activator/template/akka-cluster-sharding-scala
but it's not ported to Java

**Comment by johanandren** [comment]
We have since added samples for sharding in https://github.com/akka/akka-samples/tree/2.6/akka-sample-sharding-scala and https://github.com/akka/akka-samples/tree/2.6/akka-sample-sharding-java

Closing this
