### ISSUE TITLE
persistent actor view example does not exist anymore

### ISSUE THREAD

**Issue by jhegedus42** [akka/akka-samples#11]
[This](https://github.com/akka/akka-samples/tree/master/akka-sample-persistence-scala#persistent-actor-views) documentation refers to a file but the file is missing.

**Comment by johanandren** [comment]
Probably missed out when updated for 2.5-RC1 so README is out of date. PersistentViews were deprecated in 2.4 and will be removed in 2.5, instead you use persistence query http://doc.akka.io/docs/akka/2.4.17/scala/persistence-query.html#persistence-query-scala
