### ISSUE TITLE
Akka persistence example config references unexisting issue

### ISSUE THREAD

**Issue by francisdb** [akka/akka-samples#114]
https://github.com/akka/akka-samples/blob/d7d5908181907fbddf20943c78a9353a5e1f629b/akka-sample-persistence-scala/src/main/resources/application.conf#L8

**Comment by raboof** [comment]
Good catch. We removed some of those before but looks like we missed some.

Perhaps we should just remove the link (but not the warning). Would you like to PR?

**Comment by francisdb** [comment]
I'd like to know what was in that ticket to make that decision :-)

I'll send a PR
