### ISSUE TITLE
Akka Cluster Sample Example Improvement

### ISSUE THREAD

**Issue by shankarshastri** [akka/akka-samples#119]
### Short description

Akka Cluster Sample Example With Protobuf messaging.

### Details

Currently, the serialization that we use to serialize Akka messages is by default java serialization, and protobuf is a go-to if we want to serialize, Can we have a example with akka-cluster-sample with protobuf. I've created one, https://github.com/shankarshastri/akka-cluster-example-protocol-buffer

**Comment by patriknw** [comment]
We will update all samples that need serialization to use something else than Java serialization when updating the samples for Akka 2.6. We will mostly use [Serialization with Jackson](https://doc.akka.io/docs/akka/2.6/serialization-jackson.html) but it would be nice to show protobuf as an alternative.

You can open a PR with your changes to that sample here targeting the `2.6` branch.

When it comes to protobuf I see two alternative approaches. One is to use the generated classes as the application domain messages as you have done. That is convenient.

The other approach is to write a custom Akka serializer that converts between the protobuf classes and application domain classes. That is tedious but has the benefit that the two representations can be changed more independent of each other, for example to handle changes for rolling updates and reading data that have been persisted with older versions.

**Comment by shankarshastri** [comment]
@patriknw, I will work on the changes that I have pushed to my repository and will raise a PR for the same. I'm not sure about the second approach. Will contribute the first approach as an example. And then figure out how to work on the second one.

**Comment by shankarshastri** [comment]
@patriknw , current akka-sample-cluster-scala in 2.6 doesn't seem to work fine, as it tries to bind the port it starts failing. And uses 192.168.1.199 as host, rather than 127.0.0.1, even if specified in application.conf. Can you let me know about this issue, so that I can move forward with the same.

**Comment by shankarshastri** [comment]
Got the problem, looks like for 2.6, application.conf need to have 
```
akka.remote {
    classic.netty.tcp {
      hostname = "127.0.0.1"
      port = 0
    }
}
```
rather than 
```
akka.remote {
   netty.tcp {
      hostname = "127.0.0.1"
      port = 0
    }
}
```

**Comment by shankarshastri** [comment]
@patriknw , do we want all the examples present in cluster-sample as part of the protobuf examples or one would suffice?
Let me know about it.

**Comment by patriknw** [comment]
One is enough, thanks.
We’ll change the remoting config to Artery TCP.

**Comment by johanandren** [comment]
Closing this as all samples are on artery tcp now.
