### ISSUE TITLE
Consider moving common scala project build config and sbt logic to a samples plugin

### ISSUE THREAD

**Issue by helena** [akka/akka-samples#139]
Also look into what can we do for scalafmt conf files.

**Comment by patriknw** [comment]
A problem could be that each sample project should be self contained and with a build as simple as possible for the end consumer of the sample.

**Comment by helena** [comment]
True, though if we decided to anyway, I was thinking something like https://scalameta.org/scalafmt/docs/installation.html#share-configuration-between-builds

**Comment by patriknw** [comment]
Maybe we shouldn't add those `.scalafmt.conf` to the projects at all? I rely completely on IntelliJ format on save, and in those settings I could point to a custom file (akka/akka).

Once we have updated the samples it's not that there will be a lot of contributors that are changing them, so enforcing formatting in the build might not be needed.

**Comment by johanandren** [comment]
I think we should really try keep the builds as simple as possible no or few plugins and not even include scalafmt.
