### ISSUE TITLE
rename javaslang sample to VAVr

### ISSUE THREAD

**Issue by patriknw** [akka/akka-samples#15]

**Comment by 2m** [comment]
This should be done after vavr artifacts with the new maven coordinates are released.

**Comment by 2m** [comment]
The time has come: https://mvnrepository.com/artifact/io.vavr/vavr

**Comment by ktoso** [comment]
are you on that today @2m ?

**Comment by 2m** [comment]
Nope.

**Comment by ktoso** [comment]
Pretty please? Should be quick ;)

**Comment by johanandren** [comment]
I can do it
