### ISSUE TITLE
akka-sample-fsm-java is broken

### ISSUE THREAD

**Issue by schirmacher** [akka/akka-samples#198]
I have downloaded and run akka-sample-fsm-java. It seems that it does not seem to work. Here's my output:

    Manie has picked up Chopstick4 andChopstick0 and starts to eat
    Krasser has picked up Chopstick3 andChopstick4 and starts to eat
    Boner has picked up Chopstick1 andChopstick2 and starts to eat
    Klang has picked up Chopstick2 andChopstick3 and starts to eat
    Ghosh has picked up Chopstick0 andChopstick1 and starts to eat

Note that both Manie and Krasser pick up Chopstick4 at the same time, Boner and Klang pick up Chopstick2 at the same time and so on.

I then compared this with the output of the Scala version which is different and appears to be correct:

    Manie has picked up Chopstick5 and Chopstick1 and starts to eat
    Klang has picked up Chopstick3 and Chopstick4 and starts to eat
    Manie puts down his chopsticks and starts to think
    Klang puts down his chopsticks and starts to think
    Boner has picked up Chopstick2 and Chopstick3 and starts to eat
    Krasser has picked up Chopstick4 and Chopstick5 and starts to eat
    Krasser puts down his chopsticks and starts to think
    Boner puts down his chopsticks and starts to think
    Manie has picked up Chopstick5 and Chopstick1 and starts to eat
    Klang has picked up Chopstick3 and Chopstick4 and starts to eat
    Klang puts down his chopsticks and starts to think
    Manie puts down his chopsticks and starts to think
    Krasser has picked up Chopstick4 and Chopstick5 and starts to eat
    Boner has picked up Chopstick2 and Chopstick3 and starts to eat
    Krasser puts down his chopsticks and starts to think
    Boner puts down his chopsticks and starts to think

I also placed a breakpoint into Hakker.firstChopstickDenied: it was never called

Therefore I think that this sample code is broken, or maybe my development environment is broken.

Two more observations:
* I executed `mvn clean` in the akka-sample-fsm-java directory, which failed. Maybe there is an issue with the pom.xml? 
* the log output contains some warnings because of unhandled messages.

Complete log file is attached.
[akka-fsm-java.log](https://github.com/akka/akka-samples/files/4388281/akka-fsm-java.log)

**Comment by johanandren** [comment]
Thanks for letting us know!

I'll look into whether there is something wrong with that sample.

The maven build failing with `java.lang.ClassNotFoundException: javax.xml.bind.JAXBException` was some trixery added to set a version based on the git commit, I've created a PR fixing that.

**Comment by schirmacher** [comment]
here is a patch that works for me:

    diff -r sample.orig/Hakker.java sample/Hakker.java
    80c80
    <          .onMessage(AdaptedAnswer.class, m -> m.msg.chopstick.equals(left), (msg) ->
    ---
    >          .onMessage(AdaptedAnswer.class, m -> m.msg.isTaken() && m.msg.chopstick.equals(left), (msg) ->
    83c83
    <          .onMessage(AdaptedAnswer.class, m -> m.msg.chopstick.equals(right), (msg) ->
    ---
    >          .onMessage(AdaptedAnswer.class, m -> m.msg.isTaken() && m.msg.chopstick.equals(right), (msg) ->
    98c98
    <          .onMessage(AdaptedAnswer.class, m -> m.msg.chopstick.equals(chopstickToWaitFor), msg -> {
    ---
    >          .onMessage(AdaptedAnswer.class, m -> m.msg.isTaken(), msg -> {
    103c103
    <          .onMessage(AdaptedAnswer.class, m -> m.msg.chopstick.equals(chopstickToWaitFor), msg -> {
    ---
    >          .onMessage(AdaptedAnswer.class, m -> m.msg.isBusy(), msg -> {

**Comment by johanandren** [comment]
Thanks, I think that aligns with my fix in #200 (I also did some other cleanup while touching the samples)

**Comment by johanandren** [comment]
Merged!
