### ISSUE TITLE
Unable to compile the project in local

### ISSUE THREAD

**Issue by Swaypreet** [akka/akka-samples#212]

**Comment by johanandren** [comment]
Hi, @Swaypreet, which of sample projects are you having problems with?

**Comment by johanandren** [comment]
I see, it is the akka-sample-kafka-to-sharding-scala 

Can you let us know _how_ you tried when it failed, did you clone the entire akka-samples repo and then tried to build akka-sample-kafka-to-sharding-scala using sbt?

**Comment by Swaypreet** [comment]
Hi @johanandren ,

I had cloned only akka-sample-kafka-to-sharding-scala and then built it using sbt.

**Comment by Swaypreet** [comment]
sure, @johanandren , I can try that. will update you after trying that.

**Comment by Swaypreet** [comment]
It is working after cloning whole repo.

Thanks 
Swaypreet
