### ISSUE TITLE
CQRS with Akka 2.6 video is outdated since akka-sample-cqrs-scala has been migrated to Akka Projection

### ISSUE THREAD

**Issue by evgkarasev** [akka/akka-samples#222]
Attention to Mr. Patrik Nordwell:

Dear Patrik!
The approach you have taken to explain Event Sourcing and CQRS in series of short scala based videos is great and informative! But the target mentioned is missed since akka-sample-cqrs-scala example on which explanation the videos were built has been migrated to Akka Projection and this topic requires separate explanation. It would be great if you could find occasion to issue separate video on the topic. Adding more meaningful DB-based read model to the example, supporting queries for different aggregate roots like items or customers (to query shopping carts with certain items or customers), and adding such requests to http-get routes would be good demonstration for CQRS motivation.
Your grateful viewer,
Eugene

### Versions used 

val AkkaVersion = "2.6.7"
val AkkaPersistenceCassandraVersion = "1.0.0"
val AkkaHttpVersion = "10.1.10"
val AkkaProjectionVersion = "0.3"

### Expected Behavior

As described in video - Read side is General purpose event processor infrastructure based, where offsetStore queries logic was explicitly presented

### Actual Behavior

Read side is Akka Projection based, where offsetStore queries logic is hidden

### Relevant logs

Not applicable

### Reproducible Test Case

Not applicable

**Comment by johanandren** [comment]
Thanks for creating an issue about this, we'll get around to creating a new video, probably when akka-projections has reached an initial 1.0 release. 

In the mean time, if you find it hard to digest the updated sample together with the video, you can find the CQRS samples not using akka-projections at this commit in the repo: https://github.com/akka/akka-samples/tree/90266ca418c2218be8ef8bc0425b041994eca19a

**Comment by evgkarasev** [comment]
Thanks for prompt response! 
Sure, I got it passing through last changes. Now it's getting more clear what's going on inside akka-projections. But it's still unclear how to design canonical CQRS read side with akka-projections...
I'm trying to produce pull request to akka-sample-cqrs-scala example to add http-get routes supporting queries for different aggregate roots, to query shopping carts with certain items. It would be great if you could review my code and provide guidelines to make it right.

**Comment by renatocaval** [comment]
@evgkarasev, maybe this GitHub issue is turning into a forum question. Do you mind to post it on https://discuss.lightbend.com/? 

Ping me when doing so and I will make some time to answer there. We prefer to keep GitHub strictly for bug reports and feature requests. 

I will close it. I'm looking forward to seeing it in the forum.

Thanks for understanding.
