### ISSUE TITLE
Akka Cluster Simple - exception during creation

### ISSUE THREAD

**Issue by mrn-aglic** [akka/akka-samples#28]
I've tried to implement the akka sample, actor cluster simple which can be found here: http://www.lightbend.com/activator/template/akka-sample-cluster-java#code/src/main/resources/application.conf 
I believe my directory structure is ok: src > main > resources > application.conf.
However, when I try to run the application I get this exception: "ActorSystem [akka://ClusterSystem] needs to have a 'ClusterActorRefProvider' enabled in the configuration".
My application.conf file is the same as in the example.

**Comment by ktoso** [comment]
Thanks for reporting, we'll try to have a look; it's weird though, the param like that should indeed just work

**Comment by mrn-aglic** [comment]
I tried running the example I found on Github and it works, so the issue has to be somewhere with my project setup. Sorry for the false alarm.

**Comment by ktoso** [comment]
Great, glad it works :-)
Would have been weird if it didn't kind of :)

Closing the ticket, thanks and happy hakking!
