### ISSUE TITLE
akka-sample-camel-scala does not work with openjdk8

### ISSUE THREAD

**Issue by ketank-new** [akka/akka-samples#36]
Hi,

I have been trying to run the camel samples java and scala, using openjdk8 and sbt 0.13.13
Both the samples fail to start the application and allow me to view the akka page on browser

Executing the sample i receive the below logs

```
[ERROR] [SECURITY][08/04/2017 02:40:38.015] [some-system-akka.actor.default-dispatcher-6] [akka.actor.ActorSystemImpl(some-system)] Uncaught error from thread [some-system-akka.actor.default-dispatcher-6]: org.apache.camel.impl.HeaderFilterStrategyComponent: method <init>()V not found, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[some-system]
java.lang.NoSuchMethodError: org.apache.camel.impl.HeaderFilterStrategyComponent: method <init>()V not found

```
Some help on this would be very helpful

**Comment by patriknw** [comment]
Strange, I ran the Camel examples without problem not too long time ago, when I updated the versions. Perhaps try the latest version?

**Comment by johanandren** [comment]
We have since dropped the camel sample, so let's close this.
