### ISSUE TITLE
ReplicatedMetrics example do not cleanup a task

### ISSUE THREAD

**Issue by vasily-kirichenko** [akka/akka-samples#48]
cleanupTask.cancel() should be added here https://github.com/akka/akka-samples/blob/6ded7901f9b3fe47039c4f04cdb7016e714fc317/akka-sample-distributed-data-scala/src/main/scala/sample/distributeddata/ReplicatedMetrics.scala#L65

**Comment by patriknw** [comment]
related?
https://github.com/akka/akka-samples/issues/51

**Comment by johanandren** [comment]
This is fixed in the 2.6 branch which uses Timers instead.
