### ISSUE TITLE
Update to Akka 2.5-M2

### ISSUE THREAD

**Issue by 2m** [akka/akka-samples#5]

**Comment by ortigali** [comment]
May I take this one before "update to AbstractActor #4"?

**Comment by patriknw** [comment]
yes, great

**Comment by 2m** [comment]
@ortigali you can also investigate if https://github.com/playframework/templatecontrol works for us. Could in the end be a great tool for conducting updates of all of the samples.

**Comment by patriknw** [comment]
2.5-M2 is the latest now :)

**Comment by ortigali** [comment]
**playframework/templatecontrol** will not work for **akka-samples** yet. It can not update links in `README.md`.

**Comment by 2m** [comment]
Updated to 2.5.0.
