### ISSUE TITLE
The PersistentActorExample.scala example appears to have extraneous/incorrect code

### ISSUE THREAD

**Issue by eswenson1** [akka/akka-samples#67]
The receiveCommand method is implemented thus:

```
val receiveCommand: Receive = {
    case Cmd(data) =>
      persist(Evt(s"${data}-${numEvents}"))(updateState)
      persist(Evt(s"${data}-${numEvents + 1}")) { event =>
        updateState(event)
        context.system.eventStream.publish(event)
      }
    case "snap"  => saveSnapshot(state)
    case "print" => println(state)
  }
```
This line appears to be extraneous:
```
persist(Evt(s"${data}-${numEvents}"))(updateState)
```

It results in the examples' displaying this when run:
```
List(foo-0, foo-1, baz-2, baz-3, bar-4, bar-5, buzz-6, buzz-7)
```

Not only does this seem wrong, but it doesn't match the documentation here:  

https://doc.akka.io/docs/akka/2.5/persistence.html

**Comment by johanandren** [comment]
It's done in both the Scala and the Java sample though, I think it is on purpose to show that you can persist multiple events in sequence and that Akka persistence will make sure they are dealt with in the order they are executed. The sample here is not a 1-1 with the samples in the docs, even without that double-persist.

**Comment by patriknw** [comment]
I agree with Johan about the original intention of doing that but I think that is used very rarely (instead persistAll should be used). It would be good to simplify the example by removing the first `persist`. Would you be able to create a PR @eswenson1 ?

**Comment by eswenson1** [comment]
Sure.
