### ISSUE TITLE
akka-sample-cqrs-scala suggestions

### ISSUE THREAD

**Issue by TimMoore** [akka/akka-samples#86]
1. `CassandraSessionExtension` is used for the read side but built from the journal configuration. It might be more clear to decouple the config (even if they’re initialized from the same defaults for demo purposes) and name it something like `CassandraReadSideSessionExtension`.

2. In fact, it doesn’t show how to configure the database at all, it just relies on defaults, so readers might find it difficult it to apply this to their real applications.

3. It doesn’t exactly demonstrate CQRS, because the event processor only logs events, and doesn’t update a read model. It would be nice to demonstrate how to implement an actual read model, if only to show that there’s little magic to it (just update and query the database using CQL). I’ve seen some people confused by this, expecting some specific API for the read-side queries. Would also help demonstrate the context for how CQRS is used. Might be awkward to do as a pure command-line app, however. An Akka HTTP API server might be a more realistic example.

4. Unclear why it has this after-persist callback:
    ```case CreateSwitch(nPorts) if portStatus.isEmpty =>
      persist(SwitchCreated(nPorts)) {
        e => portStatus = createSwitch(nPorts)
      }
    ```
    Updating `portStatus` is (and should be) handled by the event handler. Similar for `SetPortStatus`.

5. Why not use `become` to model the before/after creation states and switch between command handlers? That’s closer to how we recommend people use the typed API, so will help make an easier transition.

6. `portStatus` is an `Option[Map[Int, Boolean]]` but seems like it would be more natural as `Option[IndexedSeq[Int, Boolean]]` or similar, since the port numbers are contiguous ordinals and the map is populated eagerly in `createSwitch`. For that matter, nothing ever reads the values, so the state could just be modelled as `portCount: Option[Int]`, which might be more in keeping with pure CQRS. OTOH, maybe it could include logic to avoid emitting a `PortStatusSet` event when it receives a command to set a port to its existing status value, in which case it would need to retain them.

7. Could have more comments overall, explaining the purpose of different parts, especially in the `EventProcessor`. Also, to clarify that the event processor handles each event at least once and duplicates may occur.

8. The README says “The implementation is resilient: it uses an Akka Cluster Singleton in combination with Akka Cluster Sharding.” I think it could elaborate on how it handles various failure conditions. That will help show how these tools enable building resilient services.

**Comment by TimMoore** [comment]
OK, maybe more full-fledged examples can wait until we have the projections library to handle the basics demonstrated here, but I think some discussion of the considerations could still be valuable.

> I think the state updates should be extracted to def applyEvent, that is used both from recovery and persist callbacks. That will make it more similar to Typed.

👍

Sorry, that was partly my ignorance (or forgetfulness) of the untyped Akka Persistence API… I didn't realise that `receiveRecover` is _only_ called during recovery and not automatically after each persist (though it does make sense given the name).

> In this case the receiveCommand can start with a check on portStatus.isEmpty and delegate to two different command handlers.

👍

**Comment by patriknw** [comment]
> discussion of the considerations could still be valuable

We can expand the comment around the println to explain that other things like updating a query model in another database can be done there (using `mapAsync`).

**Comment by eloots** [comment]
@TimMoore 

> It doesn’t exactly demonstrate CQRS, because the event processor only logs events

Correct; we only demonstrate side-effecting. In the real use case for which I wrote this, the side-effect is writing a message to a Kafka topic.
We could implement a more comprehensive read side, for example, one that keeps track of the number of `PortStatusSent` events and something like the average number of enabled ports per `PortStatusSent` event.

> Why not use become

As Patrik points out, this can be difficult as using `become` inherently leads to implementing a Finite State Machine (FSM) and with snapshots, one has to set the state of the FSM correctly.

> Could have more comments overall...

+1 - Can do so, specifically for the Read Model. I'm also considering recording a video demo-ing the code.

**Comment by patriknw** [comment]
obsolete
